vim.o.virtualedit = 'all'
vim.o.relativenumber = true
vim.o.number = true
vim.g.mapleader = " "
vim.o.background = 'dark'
vim.g.netrw_bufsettings = 'noma nomod nu rnu nobl nowrap ro'
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.softtabstop = 2
vim.o.expandtab = true
